# Uses git-gloss to generate notes to commits related to a pull request
name: Push notes (using git-gloss)
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: fregante/setup-git-user@v2
      - run: |
          git fetch origin "refs/notes/*:refs/notes/*"
          curl -fsSLO \
              https://sideshowbarker.github.io/git-gloss/git-gloss \
              && bash ./git-gloss
          git push origin "refs/notes/*"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
